### ISSUE TITLE
decode pbf to json ouputs NULL

### ISSUE THREAD

**Issue by vladimirghetau** [mapbox/pygeobuf#27] opened 2016-07-28 19:14 UTC
The command I'm sending is this: 

`geobuf decode < great-britain-latest-regular.pbf > great-britain-latest-regular.pbf.json`

The only output in the json file is a string called null, is anything I'm doing wrong? The file I'm working with has ~1GB.

Many thanks,
VG

**Comment by hoogw** [comment] 2016-12-01 19:49
I can't even run geobuf decode < great-britain-latest-regular.pbf > great-britain-latest-regular.pbf.json

I use windows, in windows command line, 

should I use interpreter?
>python
>>>import geobuf
>>>geobuf.decode(a.geojson, b.geojson)

got error

I also try no in interpreter,

outside interpreter, how to import geobuf modules?
>python geobuf encode()

I get error also

**Comment by sgillies** [comment] 2016-12-05 08:03
Can you provide a small data file that reproduces the error? And details about its provenance such as what software was used to create it, which protocol buffer version it uses, etc.

I just checked and the pygeobuf version 1.1.0 tests pass with protobuf 3.1.0.

**Comment by sgillies** [comment] 2016-12-05 08:12
Closing as this is very old. Apologies for missing it initially!

**Closed by sgillies** 2016-12-05 08:12 UTC

**Comment by AndreMiras** [comment] 2016-12-07 21:48
I have a similar issue using a pbf from osm2vectortiles, but also the same one from tiles.mapbox.com
```
$ wget http://osm2vectortiles-1.tileserver.com/v1/14/4823/6160.pbf
$ geobuf decode < 6160.mvt
null
```
I guess this is because `data.WhichOneof('data_type')` returns None somehow, I haven't dig more.
However the geobuf fails silently since [Decoder.decode()](https://github.com/mapbox/pygeobuf/blob/1.1.0/geobuf/decode.py#L16) has no final `else` statement with a raise Exception or something.

This is with `geobuf==1.1.0` and Python 2.7.12.
